{% set version = "9.6.9" %}
{% set sha256 = "b97952e3af02dc1e446f9c4188ff53021cc0eed7ed96f254ae6daf968c443e2e" %}

package:
  name: postgresql
  version: {{ version }}

source:
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fix_zlib_win.patch  # [win]
    - fix_gss_win32.patch  # [win32]
    - fix_gss_win64.patch  # [win64]
    # https://www.postgresql.org/message-id/attachment/43919/0002-Support-parallel-build-with-MSBuild.patch
    - symbol_tempfile.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
  host:
    - python
    - m2-bison  # [win]
    - m2-diffutils  # [win]
    - m2-flex  # [win]
    - openssl
    - perl 5.22.2.1  # [win]
    - posix  # [win]
    - readline  # [not win]
    - zlib
    - krb5  # [not osx]
    - libxml2
    - libxslt 1.1.*
    - libuuid 1.0.*  # [not win]
    - msinttypes  # [win and py27]
    - vc  # [win]
  run:
    - python
    - openssl
    - readline  # [not win]
    - zlib
    - krb5  # [not osx]
    - libxml2
    - libxslt 1.1.*
    - libuuid 1.0.*  # [not win]
    - vc  # [win]

test:
  commands:
    - pg_config
    - postgres --help
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  license_file: COPYRIGHT
  summary: 'PostgreSQL is a powerful, open source object-relational database system.'

extra:
  recipe-maintainers:
    - gillins
    - msarahan
    - ocefpaf
    - mariusvniekerk
    - sodre
