{% set version = "9.6.7" %}
{% set sha256 = "2ebe3df3c1d1eab78023bdc3ffa55a154aa84300416b075ef996598d78a624c6" %}

package:
  name: postgresql
  version: {{ version }}

source:
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fix_zlib_win.patch  # [win]
    - fix_gss_win32.patch  # [win32]
    - fix_gss_win64.patch  # [win64]
    # https://www.postgresql.org/message-id/attachment/43919/0002-Support-parallel-build-with-MSBuild.patch
    - symbol_tempfile.patch  # [win]

build:
  skip: True  # [win and py36]
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - m2-bison  # [win]
    - m2-diffutils  # [win]
    - m2-flex  # [win]
    - openssl 1.0.*
    - perl 5.22.2.1  # [win]
    - posix  # [win]
    - readline 7.0  # [not win]
    - zlib 1.2.11
    - krb5  # [not osx]
    - libxml2 2.9.*
    - libxslt 1.1.*
    - libuuid 1.0.*  # [not win]
    - msinttypes  # [win and py27]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - python
    - openssl 1.0.*
    - readline 7.0  # [not win]
    - zlib 1.2.11
    - krb5  # [not osx]
    - libxml2 2.9.*
    - libxslt 1.1.*
    - libuuid 1.0.*  # [not win]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - pg_config
    - postgres --help
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  license_file: COPYRIGHT
  summary: 'PostgreSQL is a powerful, open source object-relational database system.'

extra:
  recipe-maintainers:
    - gillins
    - msarahan
    - ocefpaf
    - mariusvniekerk
    - sodre
