travis:
  secure:
    BINSTAR_TOKEN: JXf/fPPXGfHeSPVTm5JuTFWxYHut2Euvz0Pwnh6tuvdUMREzx6a/SX/n3z+aO02PyBJmuJNjV/UBNSjhXOptbw2YTUyaYCyc9b7FJj6NVdTnE0odG9Cxi+TyxOojP/rveG0QKnK7Z6BdmmxhIHkvE9JeCRyA7nui/qecewwg4DdU32w1IB1A3AVrROYWjuF/MQcMvuEOBBoUVeOT143/ECQHG9pGOYYYROnTlFy5lRTIWUBYQ1YLWqOTd9M5M13BOv2btG+Bn7EN/B3qK/iRnCi6+i1dSIsy11m8L3zPDrxWneeOm6XSwghNCG6rdFLGCYU+SyGMBHBGBhaktp9dDEmUnrRWhjgOjV0eDpMxvj2R6IKAQyqkhyRHNEP2WtTStjjz5L/RKgcHPE0q6y5r6Q7my1B91VD3Q3hNS/2pF3ShDyubzzqL2RJDRmHVwmtUqweLIAJV+TlkfdVXXpw5EvbiqX6Tgo0HZDR5fjRhIUjR4joShHmItjrJQVC3L+xdovH0g/qJGK6w7mm/39isKy3JioPmhSy6/l/pqPwbqkqyaKQXQnr/1EfNpD66dtaQhZxbMliNik3fcas6GBoMeeEvqKst5sl9FgmfzNlgKbvwnkjPAntrqPg7ICsQDuwhMZ5MRQhMrbQIgcZwfta49DY9zSRXlccDr7bdDr+X+ek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
